### ISSUE TITLE
Render example video in readme

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/timelapse_tools#23]
Likely have to upload it to Youtube to get it to work like:

`[![Example video](https://img.youtube.com/vi/YOUTUBEID/maxresdefault.jpg)](https://youtu.be/YOUTUBEID)`

See [here](https://stackoverflow.com/a/14945782/)

**Comment by JacksonMaxfield** [comment]
Going to do this with a gif so that it just renders normally
